### ISSUE TITLE
New enum from API support

### ISSUE THREAD

**Issue by jonandersen** [Yelp/swagger-gradle-codegen#72]
Hi!

First off thank you for taking the time maintaining this library and for sharing it.

I was wondering how I can handle the case when the backend adds a new enum case to the api. In our current implementation using Moshi we fallback to null when mapping those. Using the generated code from this library our deserialization fails if we send a new enum case in the JSON response. How are you currently solving this case? Is this something that is supported? 

Thanks!

Jon

**Comment by macisamuele** [comment]
@jonandersen thanks a lot for the appreciation of the tool. That's very good ;)

Some direct and short answers first, more context below.
> How are you currently solving this case?

We're ensuring that not breaking changes are present on the swagger-specs before releasing them. We use [Yelp/swagger-spec-compatibility](https://github.com/Yelp/swagger-spec-compatibility) to ensure so.
Generally speaking backward incompatible changes should not be present on public facing APIs and the problem described reflects [swagger-spec-compatibility - RES-E003.html](https://swagger-spec-compatibility.readthedocs.io/en/latest/rules/RES-E003.html).

> Is this something that is supported?

Assuming that you're referring to the usage of null in case of unknown enum value, no this is not supported.

---

An intentional decision was made while preparing this repo: we wanted models to be mirrors of the types defined on the specs.

This means that using the approach of fallbacking to null in case of unknown enum value would not be acceptable in models like
```yaml
type: object
properties:
  e: {type: string, enum: [a, b, c]}
required: [e]
```
Even assuming that we would do something similar (aka use null if unknown value), we would not have way to distinguish between an unknown enum value and a non present value for models like
```yaml
type: object
properties:
  e: {type: string, enum: [a, b, c]}
# NOTE: required is missing here
```

Something that might be done would be to allow the definition of a default enum value to use on clients in case the received value is unknown (maybe via a vendor extension). Something that I have in mind might be
```yaml
type: object
title: Model
properties:
  e: {type: string, enum: [a, b, c]}
x-default-enum-value: a
```
So if something like `{"e": "fajkfla"}` is received it will be converted to `Model(e=Model.E.a)`.

**NOTE**: This is a possible idea, that would require some work on this library (and I have no bandwidth to implement something similar).

**Comment by jonandersen** [comment]
@macisamuele  thanks for your response on this! It does make sense that the apis shouldn't return any breaking changes. And it's something we are working towards ensuring. What we are doing now is basically a shortcut in the earlier development of the apis. 

I've looked into this issue for iOS as well and there doesn't seem to be any support for it there either. In the end it might be best to ensure our apis are non breaking than trying to change to much of Swagger.

Thanks again for your detailed response!
