### ISSUE TITLE
Missing enum import

### ISSUE THREAD

**Issue by midoriiro** [Yelp/swagger-gradle-codegen#76]
My swagger.json was generated by swashbuckle (from an asp.net core web service). I trying to generate a kotlin client from this swagger.json, the generation run successfully. But on the api generated object enum import is missing.

I followed this [sample code](https://github.com/Yelp/swagger-gradle-codegen/tree/master/samples/generated-code). Maybe I missing somethings.

You can reproduce the bug from this repository : https://github.com/midoriiro/yelp-swagger-gradle-codegen-missing-enum-import

**Comment by cortinico** [comment]
Thanks for reporting @midoriiro 
I was able to reproduce your issue and fix it in this PR: #79 

The bug was related to the return type of your endpoint:

```
"responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "object",
                "additionalProperties": {
                  "$ref": "#/definitions/MyEnum"
                }
              }
            }
          }
        }
```

Will generate a method with this return type: `Single<Map<String, Map<String, MyEnum>>>`

Previously, inner types (such as `MyEnum`) were ignored and not imported properly. The fix I proposed should cover also this scenario.
